# Generated by Django 6.0.7 on 2026-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
