# Generated by Django 6.0.7 on 2026-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='passage_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
