# Generated by Django 6.0.7 on 2026-07-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.section'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='section_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='section_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
