# Generated by Django 6.0.7 on 2026-07-17 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentattempt_current_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examset',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='manual_score',
            field=models.FloatField(blank=True, help_text='Manual band score from 0.0 to 9.0 for writing or speaking responses.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
