# Generated by Django 6.0.7 on 2026-07-17 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examset_description_examset_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='audio_response',
            field=models.FileField(blank=True, help_text='Optional speaking response. Maximum size: 20 MB.', null=True, upload_to='speaking_responses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'wav', 'webm', 'ogg'])]),
        ),
    ]
