# Generated by Django 6.0.7 on 2026-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studentanswer_audio_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='category',
            field=models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('full', 'Full Mock Test')], default='full', max_length=20),
        ),
    ]
